### ISSUE TITLE
Mixins do not work properly with association classes

### ISSUE THREAD

**Issue by TimLethbridge** [umple-ucosp/umple#1917]
The following two samples of code result in an inappropriate error 8 "Association class 'C' is missing an end".  

When solving this problem, it would be important to test other mixin cases for association classes to see if this is a more general problem.

Furthermore, if in the second file (ExamplePersistence.ump) the word 'associationClass' is replaced by the word 'class', then the compiler crashes.

```
use ExamplePersistence.ump;

class A {
}

class B {
}

associationClass C {
  * A;
  * B;
}
```

Contents of file ExamplePersistence.ump
```
external interface Serializable {}

class A {
  depend java.io.Serializable;
  isA Serializable;
  private static final long serialVersionUID = 1L;
}

class B {
  depend java.io.Serializable;
  isA Serializable;
  private static final long serialVersionUID = 2L;
}

associationClass C {
  depend java.io.Serializable;
  isA Serializable;
  private static final long serialVersionUID = 3L;
}
```

This issue was raised by Gunter Mussbacher

**Comment by TimLethbridge** [comment]
It actually doesn't matter that there is a separate file. It works the same if there is a mixin in the same file. For example:

```
class A {
}
class B {
}
associationClass C {
* A;
* B;
}

associationClass C {
}

```

It actually doesn't matter that there are 'attributes'. In fact there could be none. What matters is that an associationClass block is encountered without the 'ends'. Somehow what needs to happen is that the code that raises this error only raises it if there isn't another associationClass block for the same associationClass.

Tip to find the raising of error 14. I went to cruise.umple/src and did

grep 14 */*InternalParser*



That showed me that 14 is being raised  at

class/UmpleInternalParser_CodeClass.ump line 1443

this is the best place to start trying to understand the code



By the way the depend and isa etc are technically not attributes. But that is not important here.

**Comment by yukangyin97** [comment]
Hi, professor, with input example below 

```
class A {
}
class B {
}
associationClass C {
* A;
* B;
}

associationClass C {
}
```

We found the error "Association class 'C' is missing an end" is raised by the following if clause in `cruise.umple/src/class/UmpleInternalParser_CodeClass.ump`

```
if(singleAssocNumber == 1 || (assocNumber == 0 && singleAssocNumber == 0)){
      setFailedPosition(classToken.getPosition(), 8, classToken.getValue("name"));
      return;
}
``` 
specifically, the error is raised by `assocNumber == 0 && singleAssocNumber == 0`

will continue doing research and resolve this issue..

**Comment by ruizi** [comment]
Yes, if we change the code with this one and comments the throw error sentence
```
    if(singleAssocNumber == 1 ){
        setFailedPosition(classToken.getPosition(), 8, classToken.getValue("name"));
        return;
    }
    if(assocNumber == 0 && singleAssocNumber == 0){
        //setFailedPosition(classToken.getPosition(), 8, classToken.getValue("name"));
        return;
    }
    analyzeClass(classToken);
```

And test it with this one
```
class A {
}
class B {
}
associationClass C {
* A;
* B;
}

associationClass C {
}

```
There will be no errors. So the problem is the second condition of the if logic block.
<img width="628" alt="Screen Shot 2022-01-26 at 11 24 58 PM" src="https://user-images.githubusercontent.com/30584659/151291773-a1a70695-05f7-44d1-8cdf-035cdfbe5428.png">

Continue reading the code to try to understand the logic.

**Comment by ruizi** [comment]
Some new updates:
We use the umpleSync.jar file to run the model.ump file in terminal against the same test case shown above:
```
class A {
}
class B {
}
associationClass C {
* A;
* B;
}

associationClass C {
}
```
the console has two outputs at line 1780 means the parser run the two associationClass C in different iterations. And in this case, the empty will trigger the error we want to deal with in this issue.

![image](https://user-images.githubusercontent.com/30584659/151294107-16d08cc2-6f43-4610-8cb6-c94935569d4f.png)

Maybe, we can merge two or more same name associationClass before running analyzeClass function.

We will continue working on this one tomorrow

**Comment by yukangyin97** [comment]
### Error Tracking

1. Reported error 8 "Association class 'C' is missing an end" was thrown by the `analyzeAssociationClass` method in "cruise.umple/src/class/UmpleInternalParser_CodeClass.ump".

2. "8: 1, "http://manual.umple.org/?E008AssociationClassMissingEnd.html", Association class '{0}' is missing an end ; " in the `cruise.umple/src/en.error` makes above statement more reasonable, because "8" is equal to the error code 8 and "Association class '{0}' is missing an end" is the template of error message "Association class 'C' is missing an end".


### Error Analysis

Umple parser parsed association classes with the same name to different association classes. For example, two association classes in the code snippet below were parsed to two separate association classes
```
class A {
}
class B {
}
associationClass C {
* A;
* B;
}

associationClass C {
}
```
but they should have been parsed to only one association class. In another word, Umple parser should "merge" them into one association class, and process subsequent analysis.

### Trouble Shooting

Introduced an additional step to iterate all input tokens, for each input token that is an "associationClassDefinition", if its name is the same as the name of the currently analyzed token, then collect its sub tokens, and add them to the sub token list of currently analyzed token.

This way, for each of the association classes with the same name, Umple parser would realize each of those classes has all the attributes coming from association class with the same name. 

As a result, this addition step serves the purposes of "merging" association classes with the same name into a single association class.
